/**
 * This class is generated by jOOQ
 */
package JooqORM;


import JooqORM.tables.Stock;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Earningmanagerdb extends SchemaImpl {

    private static final long serialVersionUID = -844104310;

    /**
     * The reference instance of <code>EarningManagerDB</code>
     */
    public static final Earningmanagerdb EARNINGMANAGERDB = new Earningmanagerdb();

    /**
     * The table <code>EarningManagerDB.stock</code>.
     */
    public final Stock STOCK = JooqORM.tables.Stock.STOCK;

    /**
     * No further instances allowed
     */
    private Earningmanagerdb() {
        super("EarningManagerDB", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Stock.STOCK);
    }
}
