/**
 * This class is generated by jOOQ
 */
package JooqORM;


import JooqORM.tables.Heartbeat;
import JooqORM.tables.Stock;
import JooqORM.tables.records.HeartbeatRecord;
import JooqORM.tables.records.StockRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>EarningManagerDB</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HeartbeatRecord> KEY_HEARTBEAT_PRIMARY = UniqueKeys0.KEY_HEARTBEAT_PRIMARY;
    public static final UniqueKey<StockRecord> KEY_STOCK_PRIMARY = UniqueKeys0.KEY_STOCK_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<HeartbeatRecord> KEY_HEARTBEAT_PRIMARY = createUniqueKey(Heartbeat.HEARTBEAT, "KEY_heartbeat_PRIMARY", Heartbeat.HEARTBEAT.NAME);
        public static final UniqueKey<StockRecord> KEY_STOCK_PRIMARY = createUniqueKey(Stock.STOCK, "KEY_stock_PRIMARY", Stock.STOCK.SYMBOL);
    }
}
