/**
 * This class is generated by jOOQ
 */
package JooqORM;


import JooqORM.tables.Stock;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in EarningManagerDB
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>EarningManagerDB.stock</code>.
     */
    public static final Stock STOCK = JooqORM.tables.Stock.STOCK;
}
