# https://github.com/awslabs/aws-codedeploy-samples/blob/master/applications/SampleApp_Linux/appspec.yml

version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: target/EarningManagement-1.0-SNAPSHOT.jar
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
