# https://github.com/awslabs/aws-codedeploy-samples/blob/master/applications/SampleApp_Linux/appspec.yml

version: 0.0
os: linux
hooks:
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 300
      runas: root
