/**
 * This class is generated by jOOQ
 */
package JooqMap.tables.records;


import JooqMap.tables.Sharedstockitems;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Date;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SharedstockitemsRecord extends UpdatableRecordImpl<SharedstockitemsRecord> implements Record5<String, Integer, Date, Double, Double> {

    private static final long serialVersionUID = -587209248;

    /**
     * Create a detached SharedstockitemsRecord
     */
    public SharedstockitemsRecord() {
        super(Sharedstockitems.SHAREDSTOCKITEMS);
    }

    /**
     * Create a detached, initialised SharedstockitemsRecord
     */
    public SharedstockitemsRecord(String symbol, Integer shares, Date reportdate, Double sharedaveragecost, Double targetprice) {
        super(Sharedstockitems.SHAREDSTOCKITEMS);

        set(0, symbol);
        set(1, shares);
        set(2, reportdate);
        set(3, sharedaveragecost);
        set(4, targetprice);
    }

    /**
     * Getter for <code>library.SharedStockItems.Symbol</code>.
     */
    public String getSymbol() {
        return (String) get(0);
    }

    /**
     * Setter for <code>library.SharedStockItems.Symbol</code>.
     */
    public void setSymbol(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>library.SharedStockItems.Shares</code>.
     */
    public Integer getShares() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>library.SharedStockItems.Shares</code>.
     */
    public void setShares(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>library.SharedStockItems.Reportdate</code>.
     */
    public Date getReportdate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>library.SharedStockItems.Reportdate</code>.
     */
    public void setReportdate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>library.SharedStockItems.SharedAverageCost</code>.
     */
    public Double getSharedaveragecost() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>library.SharedStockItems.SharedAverageCost</code>.
     */
    public void setSharedaveragecost(Double value) {
        set(3, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>library.SharedStockItems.TargetPrice</code>. One year target price
     */
    public Double getTargetprice() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>library.SharedStockItems.TargetPrice</code>. One year target price
     */
    public void setTargetprice(Double value) {
        set(4, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Integer, Date, Double, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Integer, Date, Double, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Sharedstockitems.SHAREDSTOCKITEMS.SYMBOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Sharedstockitems.SHAREDSTOCKITEMS.SHARES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Sharedstockitems.SHAREDSTOCKITEMS.REPORTDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Sharedstockitems.SHAREDSTOCKITEMS.SHAREDAVERAGECOST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Sharedstockitems.SHAREDSTOCKITEMS.TARGETPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSymbol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getShares();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getReportdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getSharedaveragecost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getTargetprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedstockitemsRecord value1(String value) {
        setSymbol(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedstockitemsRecord value2(Integer value) {
        setShares(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedstockitemsRecord value3(Date value) {
        setReportdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedstockitemsRecord value4(Double value) {
        setSharedaveragecost(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedstockitemsRecord value5(Double value) {
        setTargetprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SharedstockitemsRecord values(String value1, Integer value2, Date value3, Double value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
