/**
 * This class is generated by jOOQ
 */
package JooqORM.tables.records;


import JooqORM.tables.Stock;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockRecord extends UpdatableRecordImpl<StockRecord> implements Record5<String, String, Double, Integer, Double> {

    private static final long serialVersionUID = 517458784;

    /**
     * Setter for <code>EarningManagerDB.stock.symbol</code>.
     */
    public void setSymbol(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>EarningManagerDB.stock.symbol</code>.
     */
    public String getSymbol() {
        return (String) get(0);
    }

    /**
     * Setter for <code>EarningManagerDB.stock.report_date</code>.
     */
    public void setReportDate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>EarningManagerDB.stock.report_date</code>.
     */
    public String getReportDate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>EarningManagerDB.stock.shared_average_cost</code>.
     */
    public void setSharedAverageCost(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>EarningManagerDB.stock.shared_average_cost</code>.
     */
    public Double getSharedAverageCost() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>EarningManagerDB.stock.shares</code>.
     */
    public void setShares(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>EarningManagerDB.stock.shares</code>.
     */
    public Integer getShares() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>EarningManagerDB.stock.target_price</code>.
     */
    public void setTargetPrice(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>EarningManagerDB.stock.target_price</code>.
     */
    public Double getTargetPrice() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Double, Integer, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, Double, Integer, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Stock.STOCK.SYMBOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Stock.STOCK.REPORT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Stock.STOCK.SHARED_AVERAGE_COST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Stock.STOCK.SHARES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Stock.STOCK.TARGET_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSymbol();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReportDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getSharedAverageCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getShares();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getTargetPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockRecord value1(String value) {
        setSymbol(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockRecord value2(String value) {
        setReportDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockRecord value3(Double value) {
        setSharedAverageCost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockRecord value4(Integer value) {
        setShares(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockRecord value5(Double value) {
        setTargetPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockRecord values(String value1, String value2, Double value3, Integer value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StockRecord
     */
    public StockRecord() {
        super(Stock.STOCK);
    }

    /**
     * Create a detached, initialised StockRecord
     */
    public StockRecord(String symbol, String reportDate, Double sharedAverageCost, Integer shares, Double targetPrice) {
        super(Stock.STOCK);

        set(0, symbol);
        set(1, reportDate);
        set(2, sharedAverageCost);
        set(3, shares);
        set(4, targetPrice);
    }
}
