/**
 * This class is generated by jOOQ
 */
package JooqMap;


import JooqMap.tables.Sharedstockitems;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.SharedStockItems</code>.
     */
    public static final Sharedstockitems SHAREDSTOCKITEMS = JooqMap.tables.Sharedstockitems.SHAREDSTOCKITEMS;
}
